-- =============================================================
-- Seed ICD-10 (~150 kode rawat jalan / emergensi Indonesia)
-- Idempotent — boleh dijalankan ulang.
-- =============================================================

INSERT INTO "Icd10" ("code", "description", "descriptionId", "category") VALUES
('A00','Cholera','Kolera','Penyakit infeksi & parasit'),
('A01.0','Typhoid fever','Demam tifoid','Penyakit infeksi & parasit'),
('A02.0','Salmonella enteritis','Enteritis Salmonella','Penyakit infeksi & parasit'),
('A04.9','Bacterial intestinal infection, unspecified','Infeksi usus bakterial, tak terinci','Penyakit infeksi & parasit'),
('A06.0','Acute amoebic dysentery','Disentri amuba akut','Penyakit infeksi & parasit'),
('A08.4','Viral intestinal infection, unspecified','Gastroenteritis viral, tak terinci','Penyakit infeksi & parasit'),
('A09','Diarrhoea and gastroenteritis of presumed infectious origin','Diare & gastroenteritis (dugaan infeksi)','Penyakit infeksi & parasit'),
('A15.0','Tuberculosis of lung, confirmed','TB paru, terkonfirmasi','Penyakit infeksi & parasit'),
('A16.2','Tuberculosis of lung, without mention of confirmation','TB paru, tanpa konfirmasi bakteriologi','Penyakit infeksi & parasit'),
('A37.9','Whooping cough, unspecified','Pertusis, tak terinci','Penyakit infeksi & parasit'),
('A41.9','Sepsis, unspecified','Sepsis, tak terinci','Penyakit infeksi & parasit'),
('A49.9','Bacterial infection, unspecified','Infeksi bakteri, tak terinci','Penyakit infeksi & parasit'),
('A90','Dengue fever (classical dengue)','Demam dengue','Penyakit infeksi & parasit'),
('A91','Dengue haemorrhagic fever','Demam berdarah dengue (DBD)','Penyakit infeksi & parasit'),
('B01.9','Varicella without complication','Varisela / cacar air','Penyakit infeksi & parasit'),
('B05.9','Measles without complication','Campak','Penyakit infeksi & parasit'),
('B06.9','Rubella without complication','Rubela / campak Jerman','Penyakit infeksi & parasit'),
('B08.4','Hand, foot and mouth disease','Flu Singapura (HFMD)','Penyakit infeksi & parasit'),
('B15.9','Hepatitis A without hepatic coma','Hepatitis A','Penyakit infeksi & parasit'),
('B16.9','Acute hepatitis B without delta-agent and without hepatic coma','Hepatitis B akut','Penyakit infeksi & parasit'),
('B18.1','Chronic viral hepatitis B without delta-agent','Hepatitis B kronik','Penyakit infeksi & parasit'),
('B26.9','Mumps without complication','Parotitis / gondongan','Penyakit infeksi & parasit'),
('B34.9','Viral infection, unspecified','Infeksi virus, tak terinci','Penyakit infeksi & parasit'),
('B35.0','Tinea barbae and tinea capitis','Tinea kapitis (kurap kepala)','Penyakit infeksi & parasit'),
('B35.4','Tinea corporis','Tinea korporis (kurap badan)','Penyakit infeksi & parasit'),
('B35.6','Tinea cruris','Tinea kruris (selangkangan)','Penyakit infeksi & parasit'),
('B37.3','Candidiasis of vulva and vagina','Kandidiasis vulvovaginal','Penyakit infeksi & parasit'),
('B37.9','Candidiasis, unspecified','Kandidiasis, tak terinci','Penyakit infeksi & parasit'),
('B54','Unspecified malaria','Malaria, tak terinci','Penyakit infeksi & parasit'),
('B82.9','Intestinal parasitism, unspecified','Cacingan, tak terinci','Penyakit infeksi & parasit'),
('B86','Scabies','Skabies','Penyakit infeksi & parasit'),
('D50.9','Iron deficiency anaemia, unspecified','Anemia defisiensi besi','Penyakit darah'),
('D64.9','Anaemia, unspecified','Anemia, tak terinci','Penyakit darah'),
('E03.9','Hypothyroidism, unspecified','Hipotiroid, tak terinci','Endokrin & Metabolik'),
('E05.9','Thyrotoxicosis, unspecified','Hipertiroid, tak terinci','Endokrin & Metabolik'),
('E10.9','Type 1 diabetes mellitus without complications','DM tipe 1 tanpa komplikasi','Endokrin & Metabolik'),
('E11.9','Type 2 diabetes mellitus without complications','DM tipe 2 tanpa komplikasi','Endokrin & Metabolik'),
('E11.6','Type 2 diabetes mellitus with other specified complications','DM tipe 2 dengan komplikasi','Endokrin & Metabolik'),
('E14','Unspecified diabetes mellitus','Diabetes mellitus, tak terinci','Endokrin & Metabolik'),
('E44.0','Moderate protein-energy malnutrition','Gizi kurang sedang','Endokrin & Metabolik'),
('E46','Unspecified protein-energy malnutrition','Gizi kurang, tak terinci','Endokrin & Metabolik'),
('E66.9','Obesity, unspecified','Obesitas, tak terinci','Endokrin & Metabolik'),
('E78.5','Hyperlipidaemia, unspecified','Dislipidemia, tak terinci','Endokrin & Metabolik'),
('E86','Volume depletion','Dehidrasi','Endokrin & Metabolik'),
('E87.6','Hypokalaemia','Hipokalemia','Endokrin & Metabolik'),
('F32.9','Depressive episode, unspecified','Episode depresi, tak terinci','Mental & Perilaku'),
('F41.0','Panic disorder','Gangguan panik','Mental & Perilaku'),
('F41.1','Generalized anxiety disorder','Gangguan ansietas menyeluruh','Mental & Perilaku'),
('F43.0','Acute stress reaction','Reaksi stres akut','Mental & Perilaku'),
('F45.0','Somatization disorder','Gangguan somatisasi','Mental & Perilaku'),
('F51.0','Nonorganic insomnia','Insomnia non-organik','Mental & Perilaku'),
('G43.9','Migraine, unspecified','Migrain, tak terinci','Saraf'),
('G44.2','Tension-type headache','Nyeri kepala tipe tegang','Saraf'),
('G47.0','Disorders of initiating and maintaining sleep','Insomnia','Saraf'),
('G50.0','Trigeminal neuralgia','Neuralgia trigeminal','Saraf'),
('H10.9','Conjunctivitis, unspecified','Konjungtivitis, tak terinci','Mata'),
('H11.0','Pterygium','Pterigium','Mata'),
('H16.0','Corneal ulcer','Ulkus kornea','Mata'),
('H25.9','Senile cataract, unspecified','Katarak senilis','Mata'),
('H52.1','Myopia','Miopia','Mata'),
('H52.4','Presbyopia','Presbiopia','Mata'),
('H60.9','Otitis externa, unspecified','Otitis eksterna','Telinga'),
('H65.9','Nonsuppurative otitis media, unspecified','OMA non-supuratif','Telinga'),
('H66.0','Acute suppurative otitis media','OMA supuratif','Telinga'),
('H66.9','Otitis media, unspecified','Otitis media, tak terinci','Telinga'),
('H81.1','Benign paroxysmal vertigo','BPPV / vertigo posisional','Telinga'),
('I10','Essential (primary) hypertension','Hipertensi esensial (primer)','Kardiovaskular'),
('I11.9','Hypertensive heart disease without heart failure','Penyakit jantung hipertensi','Kardiovaskular'),
('I20.9','Angina pectoris, unspecified','Angina pektoris','Kardiovaskular'),
('I21.9','Acute myocardial infarction, unspecified','Infark miokard akut','Kardiovaskular'),
('I25.9','Chronic ischaemic heart disease, unspecified','Penyakit jantung iskemik kronis','Kardiovaskular'),
('I50.9','Heart failure, unspecified','Gagal jantung, tak terinci','Kardiovaskular'),
('I63.9','Cerebral infarction, unspecified','Stroke iskemik','Kardiovaskular'),
('I64','Stroke, not specified as haemorrhage or infarction','Stroke, tak terinci','Kardiovaskular'),
('I83.9','Varicose veins of lower extremities without ulcer or inflammation','Varises tungkai','Kardiovaskular'),
('I84.9','Unspecified haemorrhoids without complication','Hemoroid, tak terinci','Kardiovaskular'),
('J00','Acute nasopharyngitis (common cold)','Common cold / pilek biasa','Pernapasan'),
('J01.9','Acute sinusitis, unspecified','Sinusitis akut','Pernapasan'),
('J02.9','Acute pharyngitis, unspecified','Faringitis akut','Pernapasan'),
('J03.9','Acute tonsillitis, unspecified','Tonsilitis akut','Pernapasan'),
('J04.0','Acute laryngitis','Laringitis akut','Pernapasan'),
('J05.0','Acute obstructive laryngitis (croup)','Kroup / laringitis akut obstruktif','Pernapasan'),
('J06.9','Acute upper respiratory infection, unspecified','ISPA, tak terinci','Pernapasan'),
('J11.1','Influenza with other respiratory manifestations, virus not identified','Influenza dengan gejala pernapasan','Pernapasan'),
('J18.9','Pneumonia, unspecified organism','Pneumonia, tak terinci','Pernapasan'),
('J20.9','Acute bronchitis, unspecified','Bronkitis akut','Pernapasan'),
('J21.9','Acute bronchiolitis, unspecified','Bronkiolitis akut','Pernapasan'),
('J30.4','Allergic rhinitis, unspecified','Rinitis alergi','Pernapasan'),
('J35.0','Chronic tonsillitis','Tonsilitis kronik','Pernapasan'),
('J40','Bronchitis, not specified as acute or chronic','Bronkitis, tak terinci','Pernapasan'),
('J44.9','Chronic obstructive pulmonary disease, unspecified','PPOK','Pernapasan'),
('J45.9','Asthma, unspecified','Asma, tak terinci','Pernapasan'),
('J45.0','Predominantly allergic asthma','Asma alergik','Pernapasan'),
('J46','Status asthmaticus','Status asmatikus','Pernapasan'),
('K02.9','Dental caries, unspecified','Karies gigi','Pencernaan'),
('K05.0','Acute gingivitis','Gingivitis akut','Pencernaan'),
('K12.0','Recurrent oral aphthae','Sariawan / stomatitis aftosa','Pencernaan'),
('K21.9','Gastro-oesophageal reflux disease without oesophagitis','GERD','Pencernaan'),
('K25.9','Gastric ulcer, unspecified','Ulkus lambung','Pencernaan'),
('K27.9','Peptic ulcer, site unspecified','Ulkus peptikum','Pencernaan'),
('K29.7','Gastritis, unspecified','Gastritis, tak terinci','Pencernaan'),
('K30','Functional dyspepsia','Dispepsia fungsional','Pencernaan'),
('K35.8','Acute appendicitis, unspecified','Apendisitis akut','Pencernaan'),
('K52.9','Noninfective gastroenteritis and colitis, unspecified','Gastroenteritis non-infeksi','Pencernaan'),
('K57.9','Diverticular disease, unspecified','Penyakit divertikular','Pencernaan'),
('K59.0','Constipation','Konstipasi','Pencernaan'),
('K80.2','Calculus of gallbladder without cholecystitis','Batu empedu tanpa kolesistitis','Pencernaan'),
('L01.0','Impetigo','Impetigo','Kulit'),
('L02.9','Cutaneous abscess, furuncle and carbuncle, unspecified','Abses / furunkel / karbunkel kulit','Kulit'),
('L03.9','Cellulitis, unspecified','Selulitis','Kulit'),
('L20.9','Atopic dermatitis, unspecified','Dermatitis atopik','Kulit'),
('L21.9','Seborrhoeic dermatitis, unspecified','Dermatitis seboroik','Kulit'),
('L23.9','Allergic contact dermatitis, unspecified cause','Dermatitis kontak alergi','Kulit'),
('L24.9','Irritant contact dermatitis, unspecified cause','Dermatitis kontak iritan','Kulit'),
('L29.9','Pruritus, unspecified','Pruritus, tak terinci','Kulit'),
('L30.9','Dermatitis, unspecified','Dermatitis, tak terinci','Kulit'),
('L40.9','Psoriasis, unspecified','Psoriasis','Kulit'),
('L50.9','Urticaria, unspecified','Urtikaria, tak terinci','Kulit'),
('L70.0','Acne vulgaris','Akne vulgaris','Kulit'),
('M10.9','Gout, unspecified','Gout, tak terinci','Muskuloskeletal'),
('M19.9','Osteoarthritis, unspecified','Osteoartritis, tak terinci','Muskuloskeletal'),
('M25.5','Pain in joint','Nyeri sendi','Muskuloskeletal'),
('M54.5','Low back pain','Nyeri pinggang bawah (LBP)','Muskuloskeletal'),
('M54.2','Cervicalgia','Nyeri leher','Muskuloskeletal'),
('M62.6','Muscle strain','Strain otot','Muskuloskeletal'),
('M79.1','Myalgia','Mialgia','Muskuloskeletal'),
('N10','Acute tubulo-interstitial nephritis','Pielonefritis akut','Genitourinaria'),
('N18.9','Chronic kidney disease, unspecified','Penyakit ginjal kronik (CKD)','Genitourinaria'),
('N20.0','Calculus of kidney','Batu ginjal','Genitourinaria'),
('N23','Unspecified renal colic','Kolik renal','Genitourinaria'),
('N30.0','Acute cystitis','Sistitis akut','Genitourinaria'),
('N39.0','Urinary tract infection, site not specified','Infeksi saluran kemih (ISK)','Genitourinaria'),
('N40','Hyperplasia of prostate','BPH (pembesaran prostat)','Genitourinaria'),
('N76.0','Acute vaginitis','Vaginitis akut','Genitourinaria'),
('N91.2','Amenorrhoea, unspecified','Amenorea, tak terinci','Genitourinaria'),
('N94.6','Dysmenorrhoea, unspecified','Dismenorea, tak terinci','Genitourinaria'),
('O15.9','Eclampsia, unspecified as to time period','Eklampsia','Kehamilan'),
('O20.0','Threatened abortion','Abortus iminens','Kehamilan'),
('O21.0','Mild hyperemesis gravidarum','Hiperemesis gravidarum ringan','Kehamilan'),
('O80','Single spontaneous delivery','Persalinan spontan tunggal','Kehamilan'),
('P07.3','Other preterm infants','Bayi prematur (lainnya)','Perinatal'),
('P22.9','Respiratory distress of newborn, unspecified','Gangguan napas neonatus','Perinatal'),
('P59.9','Neonatal jaundice, unspecified','Ikterus neonatorum','Perinatal'),
('R05','Cough','Batuk','Gejala & Tanda'),
('R07.4','Chest pain, unspecified','Nyeri dada, tak terinci','Gejala & Tanda'),
('R10.4','Other and unspecified abdominal pain','Nyeri perut, tak terinci','Gejala & Tanda'),
('R11','Nausea and vomiting','Mual dan muntah','Gejala & Tanda'),
('R19.7','Diarrhoea, unspecified','Diare, tak terinci','Gejala & Tanda'),
('R21','Rash and other nonspecific skin eruption','Ruam kulit','Gejala & Tanda'),
('R42','Dizziness and giddiness','Pusing / vertigo','Gejala & Tanda'),
('R50.9','Fever, unspecified','Demam, tak terinci','Gejala & Tanda'),
('R51','Headache','Sakit kepala','Gejala & Tanda'),
('R52.9','Pain, unspecified','Nyeri, tak terinci','Gejala & Tanda'),
('R53','Malaise and fatigue','Lemas / fatik','Gejala & Tanda'),
('R55','Syncope and collapse','Sinkop','Gejala & Tanda'),
('R56.0','Febrile convulsions','Kejang demam','Gejala & Tanda'),
('S00.9','Superficial injury of head, part unspecified','Cedera superfisial kepala','Cedera'),
('S01.9','Open wound of head, part unspecified','Luka terbuka kepala','Cedera'),
('S06.0','Concussion','Komosio cerebri','Cedera'),
('S52.9','Fracture of forearm, unspecified','Fraktur lengan bawah','Cedera'),
('S72.9','Fracture of femur, unspecified','Fraktur femur','Cedera'),
('S81.9','Open wound of lower leg, part unspecified','Vulnus / luka tungkai bawah','Cedera'),
('T14.0','Superficial injury of unspecified body region','Cedera superfisial, tak terinci','Cedera'),
('T14.1','Open wound of unspecified body region','Vulnus / luka terbuka, tak terinci','Cedera'),
('T63.4','Toxic effect of venom of other arthropods','Gigitan serangga','Cedera'),
('T78.4','Allergy, unspecified','Alergi, tak terinci','Cedera'),
('T78.0','Anaphylactic shock due to adverse food reaction','Syok anafilaktik makanan','Cedera'),
('T78.2','Anaphylactic shock, unspecified','Syok anafilaktik, tak terinci','Cedera'),
('Z00.0','General medical examination','Pemeriksaan kesehatan umum','Faktor lain (Z)'),
('Z23','Need for immunization against single bacterial diseases','Imunisasi','Faktor lain (Z)'),
('Z34.9','Supervision of normal pregnancy, unspecified','Pengawasan kehamilan normal (ANC)','Faktor lain (Z)'),
('Z39.2','Routine postpartum follow-up','Kontrol postpartum rutin','Faktor lain (Z)')
ON CONFLICT ("code") DO NOTHING;

-- Verifikasi
SELECT COUNT(*) AS total_icd10 FROM "Icd10";
